# keybinds.toml
# Defines keybindings depending on modes

[twist]
# Cartesian control
# For vector movement, set 2 keys for each axis
stop = "space"

[twist.linear]
scale = 0.1
x = ["w", "s"]
y = ["a", "d"]
z = ["q", "e"]

[twist.angular]
scale = 0.5
x = ["W", "S"]
y = ["A", "D"]
z = ["Q", "E"]
