# keybinds.toml
# Defines keybindings depending on modes

[twist]
# Cartesian control
# For vector movement, set 2 keys for each axis
stop = "space"

[twist.linear]
x = ["w", "s"]
y = ["a", "d"]
z = ["q", "e"]

[twist.angular]
x = ["W", "S"]
y = ["A", "D"]
z = ["Q", "E"]

[joint]
# Joint space control of a 6-DOF manipulator
stop = "space"

0 = ["1", "!"]
1 = ["2", "@"]
2 = ["3", "#"]
3 = ["4", "$"]
4 = ["5", "%"]
5 = ["6", "^"]
