name: Linting
on:
  pull_request:
    branches: [main]


jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: shellcheck --shell=bash --external-sources --format=gcc --color=always *.sh
  
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v9

  cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "src/**/*.h,src/**/*.c,test/**/*.c"
